//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalManagementEntities : DbContext
    {
        public HospitalManagementEntities()
            : base("name=HospitalManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BedsParamtersTb> BedsParamtersTbs { get; set; }
        public virtual DbSet<BedTypesTb> BedTypesTbs { get; set; }
        public virtual DbSet<CategoryTb> CategoryTbs { get; set; }
        public virtual DbSet<CurrentBedTb> CurrentBedTbs { get; set; }
        public virtual DbSet<CurrentEquipmentTb> CurrentEquipmentTbs { get; set; }
        public virtual DbSet<CurrentOperatingRoomTb> CurrentOperatingRoomTbs { get; set; }
        public virtual DbSet<CurrentWorkForceTb> CurrentWorkForceTbs { get; set; }
        public virtual DbSet<EquipmentParamtersTb> EquipmentParamtersTbs { get; set; }
        public virtual DbSet<EquipmentTypeTb> EquipmentTypeTbs { get; set; }
        public virtual DbSet<MainSupplyTb> MainSupplyTbs { get; set; }
        public virtual DbSet<PlannedBedsTb> PlannedBedsTbs { get; set; }
        public virtual DbSet<PlannedEquipmentTb> PlannedEquipmentTbs { get; set; }
        public virtual DbSet<PlannedOperatingRoomTb> PlannedOperatingRoomTbs { get; set; }
        public virtual DbSet<PlannedWorkforceTb> PlannedWorkforceTbs { get; set; }
        public virtual DbSet<SubCategoryTb> SubCategoryTbs { get; set; }
        public virtual DbSet<UserTb> UserTbs { get; set; }
        public virtual DbSet<WorkforceCertifiedJobTypeTb> WorkforceCertifiedJobTypeTbs { get; set; }
        public virtual DbSet<WorkforceCertifiedSpecialityTb> WorkforceCertifiedSpecialityTbs { get; set; }
        public virtual DbSet<WorkforceCertifiedSubSpecialityTb> WorkforceCertifiedSubSpecialityTbs { get; set; }
        public virtual DbSet<WorkforceClinicalProgramTb> WorkforceClinicalProgramTbs { get; set; }
        public virtual DbSet<WorkforceCurrentJobTypeTb> WorkforceCurrentJobTypeTbs { get; set; }
        public virtual DbSet<WorkforceCurrentSpecialityTb> WorkforceCurrentSpecialityTbs { get; set; }
        public virtual DbSet<WorkforceCurrentSubSpecialityTb> WorkforceCurrentSubSpecialityTbs { get; set; }
        public virtual DbSet<WorkforceGradeTb> WorkforceGradeTbs { get; set; }
        public virtual DbSet<WorkforceParamtersTb> WorkforceParamtersTbs { get; set; }
    }
}
