//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlannedWorkforceTb
    {
        public int PlannedWorkforceId { get; set; }
        public int CategoryId { get; set; }
        public int SubCategoryId { get; set; }
        public Nullable<int> CurrentSpecialityId { get; set; }
        public Nullable<int> CertifiedSpecialityId { get; set; }
        public Nullable<int> CertifiedSubSpecialityId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<System.DateTime> YearOfJoining { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
