//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkforceClinicalProgramTb
    {
        public int ClinicalProgramId { get; set; }
        public int CategoryId { get; set; }
        public int SubCategoryId { get; set; }
        public string ProgramName { get; set; }
        public Nullable<int> Duration { get; set; }
    }
}
