//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkforceParamtersTb
    {
        public int WorkforceParamterId { get; set; }
        public int CategoryId { get; set; }
        public int SubCategoryId { get; set; }
        public Nullable<int> CurrentSpecialityId { get; set; }
        public Nullable<int> CurrentSubSpecialityId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public string Gender { get; set; }
        public Nullable<double> AttritionRate { get; set; }
        public Nullable<double> AbsentismRate { get; set; }
        public Nullable<int> RetirementAge { get; set; }
        public Nullable<int> FTEPerDayHours { get; set; }
    }
}
